version: '3.8'

services:
  spa:
    container_name: spa
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - nodemodules:/app/node_modules
volumes:
  nodemodules:
